name: "Swift install"
description: "Install Swift"

inputs:
    swift-prefix:
        description: "The URL prefix to download the Swift toolchain from, \
            if installing Swift. The string should be a valid directory under \
            download.swift.org, such as 'swift-5.10.1-release/ubuntu2404/swift-5.10.1-RELEASE'"
        required: true
        type: string

    swift-id:
        description: "The Swift toolchain version to install. This should be a full toolchain \
          identifier, including the platform, like 'swift-5.10.1-RELEASE-ubuntu24.04'"
        required: true
        type: string

runs:
    using: composite
    steps:
        -   name: Cache Swift toolchain
            id:   cache_swift
            uses: actions/cache@v2
            with:
                path: "${{ env.HOME }}/swift/swift.tar.gz"
                key: "swift:${{ inputs.swift-id }}"

        -   name: Download Swift
            shell: bash
            if: steps.cache_swift.outputs.cache-hit != 'true'
            env:
                SWIFT_PREFIX: ${{ inputs.swift-prefix }}
                SWIFT_ID: ${{ inputs.swift-id }}
            run: |
                mkdir -p $HOME/swift/$SWIFT_ID
                curl https://download.swift.org/$SWIFT_PREFIX/$SWIFT_ID.tar.gz \
                    --output $HOME/swift/swift.tar.gz

        -   name: Install Swift
            shell: bash
            env:
                SWIFT_ID: ${{ inputs.swift-id }}
            run: |
                mkdir -p $HOME/swift/$SWIFT_ID
                tar -xzf $HOME/swift/swift.tar.gz -C $HOME/swift/$SWIFT_ID --strip 1
                echo "SWIFT_INSTALLATION=$HOME/swift/$SWIFT_ID/usr" >> $GITHUB_ENV
                echo "$HOME/swift/$SWIFT_ID/usr/bin" >> $GITHUB_PATH

        -   name: Check Swift
            shell: bash
            run: |
                $SWIFT_INSTALLATION/bin/swift --version
                cat $GITHUB_PATH
                swift --version
