name: self test

on:
    push:
        branches: [ master ]

    pull_request:
        branches: [ master ]

jobs:
    linux:
        runs-on: ubuntu-24.04
        name: Ubuntu 24.04

        steps:
            -   name: Install Swift
                uses: tayloraswift/swift-install-action@master
                with:
                    swift-prefix: "swift-6.0-release/ubuntu2404/swift-6.0-RELEASE"
                    swift-id: "swift-6.0-RELEASE-ubuntu24.04"

            -   name: Check Swift
                run: swift --version

    macos:
        runs-on: macos-14
        name: macOS

        steps:
            -   name: Install Swift
                uses: tayloraswift/swift-install-action@master
                with:
                    swift-prefix: "swift-6.0-release/xcode/swift-6.0-RELEASE"
                    swift-id: "swift-6.0-RELEASE-osx"

            -   name: Check Swift
                run: swift --version
