name: self test

on:
    push:
        branches: [ master ]

    pull_request:
        branches: [ master ]

jobs:
    linux:
        runs-on: ubuntu-24.04
        name: Ubuntu 24.04

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Install Swift
                uses: ./
                with:
                    swift-prefix: "swift-6.1-release/ubuntu2404/swift-6.1-RELEASE"
                    swift-id: "swift-6.1-RELEASE-ubuntu24.04"

            -   name: Check Swift
                run: swift --version

    macos:
        runs-on: macos-14
        name: macOS

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Install Swift
                uses: ./
                with:
                    swift-prefix: "swift-6.1-release/xcode/swift-6.1-RELEASE"
                    swift-id: "swift-6.1-RELEASE"

            -   name: Check Swift
                run: swift --version
